new table row added try2
mhiliri/collaborating-practice pull request #10
Opened 2022-12-14 05:30 UTC by iFernandezE

2022-12-14 13:27 UTC, mhiliri approved these changes

2022-12-14 14:01 UTC, mhiliri requested changes
Please fix the merge conflict

2022-12-14 14:01 UTC, mhiliri commented on index.html
> +    <tr>
Please fix the merge conflict

2022-12-16 03:45 UTC, iFernandezE commented on index.html
> +    <tr>
I have fixed the conflict

2022-12-16 13:52 UTC, mhiliri approved these changes

2022-12-16 13:52 UTC, merged