Pokemon Weedle was added to the pokemon list.
mhiliri/collaborating-practice pull request #9
Opened 2022-12-14 05:25 UTC by AndresMamaniMendoza

2022-12-14 13:25 UTC, mhiliri approved these changes

2022-12-14 13:38 UTC, mhiliri commented
Please fix the merge conflict

2022-12-14 13:41 UTC, mhiliri requested changes

2022-12-14 13:41 UTC, mhiliri commented on index.html
> +    <tr>
Please fix the merge conflict

2022-12-16 06:18 UTC, AndresMamaniMendoza commented on index.html
> +    <tr>
Conflicts were solved.

2022-12-19 11:49 UTC, mhiliri approved these changes

2022-12-19 11:49 UTC, mhiliri commented on index.html
> +         </tr>
Please update you branch with main branch and fix the merge conflict

2022-12-19 11:49 UTC, merged